# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataAW
                                 A QGIS plugin
 DataAW compares two files using area-weighted data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-03
        copyright            : (C) 2024 by Eunice Barbosa
        email                : e_kbb8@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Eunice Barbosa'
__date__ = '2024-12-03'
__copyright__ = '(C) 2024 by Eunice Barbosa'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataAW class from file DataAW.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DataAW import DataAWPlugin
    return DataAWPlugin()
